[[main]]
  name = "Logs"
  pageRef = "posts"
  weight = 10

[[main]]
  name = "Position"
  pageRef = "position"
  weight = 20

[[main]]
  name = "Fleet"
  pageRef = "fleet"
  weight = 30

[[main]]
  name = "Buildouts"
  pageRef = "loadouts"
  weight = 40

[[main]]
  name = "Ranks"
  pageRef = "ranks"
  weight = 50

[[main]]
  name = "Carrier"
  pageRef = "carrier"
  weight = 60

[[main]]
  name = "About"
  pageRef = "about"
  weight = 70
